   10 WRITE "Enter string to test> ": INPUT a$
   20 IF ISUPPER(a$) THEN PRINT "UPPERCASE" FI
   30 IF ISLOWER(a$) THEN PRINT "LOWERCASE" FI
   40 IF ISALPHA(a$) THEN PRINT "ALPHA" FI
   50 IF ISALNUM(a$) THEN PRINT "ALPHANUMERIC" FI
   60 IF ISDIGIT(a$) THEN PRINT "DIGITS" FI
   70 IF ISNUM(a$) THEN PRINT "NUMBER" FI
   80 IF ISBLANK(a$) THEN PRINT "BLANK" FI
   90 GOTO 10
